import { useState } from "react";

import Sidebar from "./Sidebar";
import CodeGenerator from "./CodeGenerator";
import ChatPanel from "./ChatPanel";
import Message from "./Message";

export default function Dashboard() {
  const [prompt, setPrompt] = useState("");
  const [language, setLanguage] = useState("");

  const [generatedCode, setGeneratedCode] = useState("");

  const [optimizedCode, setOptimizedCode] = useState("");

  const [history, setHistory] = useState([]);

  return (
    <div className="min-h-screen bg-slate-950 text-white flex">

      <Sidebar />

      <main className="flex-1 overflow-y-auto">

        {/* Hero */}

        <div className="border-b border-slate-800 bg-slate-900">

          <div className="max-w-7xl mx-auto px-12 py-12">

            <h1 className="text-5xl font-bold">
              Welcome to CodeMentor AI
            </h1>

            <p className="text-slate-400 text-xl mt-4 max-w-3xl">
              Generate interview-quality code, understand every line,
              ask AI mentor questions and create professional revision
              notes for future learning.
            </p>

          </div>

        </div>

        <div className="max-w-7xl mx-auto p-10 space-y-10">

          {/* Generator */}

          <section className="bg-slate-900 rounded-3xl border border-slate-800 shadow-xl p-8">

            <CodeGenerator
              setPrompt={setPrompt}
              setLanguage={setLanguage}
              setGeneratedCode={setGeneratedCode}
              setOptimizedCode={setOptimizedCode}
            />

          </section>

          {/* Generated */}

          {generatedCode && (

            <section className="rounded-3xl border border-slate-800 overflow-hidden bg-slate-900 shadow-xl">

              <div className="bg-slate-800 px-8 py-5">

                <h2 className="text-3xl font-bold">
                  Generated Solution
                </h2>

                <p className="text-slate-400 mt-2">
                  Initial solution generated by CodeMentor AI.
                </p>

              </div>

              <div className="p-8">

                <Message
                  message={{
                    role: "assistant",
                    content: generatedCode,
                  }}
                />

              </div>

            </section>

          )}

          {/* Optimized */}

          {optimizedCode && (

            <section className="rounded-3xl border border-slate-800 overflow-hidden bg-slate-900 shadow-xl">

              <div className="bg-slate-800 px-8 py-5">

                <h2 className="text-3xl font-bold">
                  Optimized Solution
                </h2>

                <p className="text-slate-400 mt-2">
                  Improved solution with better performance and coding
                  practices.
                </p>

              </div>

              <div className="p-8">

                <Message
                  message={{
                    role: "assistant",
                    content: optimizedCode,
                  }}
                />

              </div>

            </section>

          )}

          {/* Mentor */}

          {generatedCode && (

            <section className="rounded-3xl border border-slate-800 bg-slate-900 shadow-xl overflow-hidden">

              <div className="bg-slate-800 px-8 py-5">

                <h2 className="text-3xl font-bold">
                  AI Mentor
                </h2>

                <p className="text-slate-400 mt-2">
                  Ask only questions related to the generated solution.
                </p>

              </div>

              <div className="p-8">

                <ChatPanel
                  code={generatedCode}
                  prompt={prompt}
                  language={language}
                  history={history}
                  setHistory={setHistory}
                />

              </div>

            </section>

          )}

        </div>

      </main>

    </div>
  );
}